### Transforming Code Into Idiomatic Python
* Replace traditional index manupulation with Python core looping idiomatic


In [1]:
# Looping over a range of numbers - Traditional Approach
for i in [0,1,2,3,4,5]:
   print(i**2,end=" ")

0 1 4 9 16 25 

In [2]:
# Idotiomatic Programming
for i in range(6):
   print(i**2,end=" ")
   


0 1 4 9 16 25 

### Looping Over A Collection¶


In [3]:
colors=['red','green','yellow','purple']
for i in range(len(colors)):
   print(colors[i],end=" ")


red green yellow purple 

In [4]:
for color in colors:
   print(color,end=" ")


red green yellow purple 

 ###  Looping Backward


In [5]:
colors=['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
   print(colors[i],end=" ")


purple yellow green red 

In [6]:
for color in reversed(colors):
   print(color,end=" ")

purple yellow green red 

### Pandas

In [7]:
import pandas as pd

In [8]:
dt={'Id':[11,12,13,14,15],
   'first_name':['A','B','C','D','E'],
   'Company':['aa','bb','cc','dd','ee'],
   'Address':['hyd','hyd','hyd','hyd','hyd']}
mydt=pd.DataFrame(dt)
print(mydt)

   Id first_name Company Address
0  11          A      aa     hyd
1  12          B      bb     hyd
2  13          C      cc     hyd
3  14          D      dd     hyd
4  15          E      ee     hyd


In [10]:
import os

In [14]:
os.chdir('C:\Users\ece - 3\Desktop\vikas python') # saves to certain location

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-14-4b5f8ddd5e2f>, line 1)

In [15]:
mydt.to_csv('WorkingFile.csv',index=False)

### Reading the data from CSV File 

In [18]:
mydata=pd.read_csv('WorkingFile.csv',skiprows=1,
                  names=['CustId','Name','Company','Address'])

In [19]:
print(mydata)

   CustId Name Company Address
0      11    A      aa     hyd
1      12    B      bb     hyd
2      13    C      cc     hyd
3      14    D      dd     hyd
4      15    E      ee     hyd


### Print Only Two Columns
### Print the large value from CustID column - max
### Print the least value from CustID column - min
### Average of CustID column - sum(li)/len(li)
### Numpy Package-
* Numpy arrays are like Python List
* Numpy is also a data structure
* Short for "Numeric Python"


In [20]:
import numpy as np

In [21]:
li=[1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [22]:
array=np.array(li)
print(array)

[1 2 3 4 5]


In [25]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)
a1.reshape(3,2)

(2, 3)
(3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [28]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
